### ISSUE TITLE
Error occurred while enabling

### ISSUE THREAD

**Issue by Atten007** [TomasGnG/DynamicSeasons#1]
Hello,

I found a bug in your plugin:

When the plugin enables itself, it shows the error "Can't invoke org.bukkit.World.setGameRule(org.bukkit.GameRule, Object) because "world" is null.

Can this be fixed?

Greetings,
Atten 😄

**Comment by TomasGnG** [comment]
Hey, can you paste your config.yml? 
It just says, that a world in the list couldnt load

**Comment by TomasGnG** [comment]
Yep, just recreated this error. A world name in your config.yml is not valid. 
Thanks for letting me know! I will create a better error message next update, which will be coded tomorrow.
